live_config_reload: true

env:
  TERM: screen-256color

shell:
  program: /usr/local/bin/zsh
  args:
    - '--login'

selection:
  save_to_clipboard: true

window:
  dimensions:
    columns: 120
    lines: 40
  padding:
    x: 5
    y: 5

font:
  normal:
    family: 'Hack Nerd Font Mono'
  bold:
    family: 'Hack Nerd Font Mono'
  italic:
    family: 'Hack Nerd Font Mono'
  size: 13

render_timer: false

custom_cursor_colors: true
hide_cursor_when_typing: false
cursor_style: Block

schemes:
  one-dark-readable: &one-dark-readable
    primary:
      background: '0x21252b'
      foreground: '0xfafafa'
    cursor:
      text: '0xabb2bf'
      cursor: '0xabb2bf'
    selection:
      text: '0xffffff'
      background: '0x767676'
    normal:
      black: '0x21252b'
      red: '0xe06c75'
      green: '0x98c379'
      yellow: '0xe5c07b'
      blue: '0x61afef'
      magenta: '0xc678dd'
      cyan: '0x56b6c2'
      white: '0xfafafa'
    bright:
      black: '0x767676'
      red: '0xe06c75'
      green: '0x98c379'
      yellow: '0xe5c07b'
      blue: '0x61afef'
      magenta: '0xc678dd'
      cyan: '0x56b6c2'
      white: '0xffffff'

colors: *one-dark-readable
